# 이 action의 이름이다
name: aws

# 누가 이 action을 만들었는가
author: seongjun-actions

# 이 action에 대한 설명
description: "Use aws job in github action"

# 이 action에 주입할 수 있는 변수값(변수값을 주입받지 못하면 기본값을 사용한다. 다만 required라서 무조건 주입해야할 듯)
# 사용하는 곳에서 with 키워드를 통해 변수값을 주입한다.
inputs:
  AWS_REGION:
    description: "set aws region"
    required: true
    default: "ap-northeast-2"
  AWS_ROLE_TO_ASSUME:
    description: "set aws role to assume"
    required: true
    default: "GithubActions"

runs:
  # using: "composite"가 있어야만 composite action을 사용가능하다.
  using: "composite"

  steps:
    # AWS 권한을 얻기 위해 aws action을 사용한다. 이 때 aws에 access하기 위한 정보(region, role)를 with로 전달했다.
    - name: Configure AWS Credentials
      id: credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.AWS_REGION }}
        role-to-assume: ${{ inputs.AWS_ROLE_TO_ASSUME }}
