name: slack
author: seongjun-actions
description: "Use slack job in github action"
inputs:
  DEPLOY_STEP_STATUS:
    description: "deploy step status"
    required: true
    default: "success"
  ENVIRONMENT:
    description: "set environment"
    required: true
    default: "dev"
  SLACK_WEBHOOK_URL:
    description: "set slack webhook url"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - name: notify
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "text": "message",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Environment : ${{ inputs.environment }}, Deploy Result : ${{ inputs.DEPLOY_STEP_STATUS }}, Repository : ${{ github.repository }}."
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
